config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/fb_channel' => 'home#fb_channel', :as => 'fb_channel'

  get "info/historianew"

  get 'info/' => "info#index", as: :info

  get 'event/:id' => 'events#show', as: :event
  get 'event/:id/logged' => 'events#logged', as: :logged
  get 'join/:id' => 'events#join', as: :join

  get 'calendar' => 'home#calendar', as: :calendar

  get 'event/entry_list/:id' => 'admin/events#entry_list', as: :entry_list

  get 'event/entry_list_to_xlsx/:id' => 'admin/events#entry_list_to_xlsx', as: :entry_list_to_xlsx

  get 'info/send_mail' => 'info#send_mail', as: :info_send_mail
  
  get 'responsable_autocomplete' => 'events#responsable_autocomplete'

  get 'brigades/dashboard' => 'brigades#dashboard', as: :brigades_dash
  get 'brigades/brigades' => 'brigades#index', as: :brigades_index
  get 'brigades/:id/view_event' => 'brigades#view_event', as: :view_event
  get 'brigades/:id/view_brigade' => 'brigades#view_brigade', as: :view_brigade
  post 'brigades/:id/add_brigadist' => 'brigades#add_brigadist', as: :add_brigadist
  post 'brigades/:id/remove_brigadist' => 'brigades#remove_brigadist', as: :remove_brigadist
  get 'admin/volunteers/volunteer_filter' => 'admin/volunteers#volunteer_filter', as: :volunteer_filter
  get 'admin/children/child_filter' => 'admin/children#child_filter', as: :child_filter
  get 'admin/polls/poll_filter' => 'admin/polls#poll_filter', as: :poll_filter
  get 'admin/events/events_filter' => 'admin/events#events_filter', as: :events_filter
  get 'admin/users/users_filter' => 'admin/users#users_filter', as: :users_filter
  
  namespace :admin do
    resource :dash

    resources :users do
      member do
        get :login_as, :resend_activation, :to_csv
        post :make_admin
      end
      collection do
        get :chart_data
      end
    end

    resources :volunteers do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv
      end
    end
    
    resources :children do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv

      end

    end

    resources :polls do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv
        post :from_xlsx
      end
    end

    resources :brigades
    resources :events do
      member do
        get :edit_new
        post :add_image
        delete :destroy_image, :remove_participant
      end
    end
    get 'responsable_autocomplete' => 'events#responsable_autocomplete'

    resources :hospitals do 

    end

  end

  get '/return_to_admin' => 'home#return_to_admin', :as => :return_to_admin

end

app/models/event.rb
class Event < ActiveRecord::Base

  include ActionView::Helpers

  EVENT_TYPES = ['Inducción', 'Voluntariado']
  EVENT_STATES = ['Activo', 'Inactivo']
=begin
  attr_accessible :name, :description, :spaces, :used, :event_type, 
                  :event_type_id, :event_date, :state, :place,  
                  :responsable_id, :city_id, :city, :requires_adult, 
                  :area, :area_id, :role, :activation_date, :brigade_id
=end

  has_many :events_users, dependent: :destroy
  has_many :users, through: :events_users
  has_many :event_images, dependent: :destroy
  belongs_to :responsable, class_name: 'User'
  belongs_to :city
  belongs_to :area
  belongs_to :event_type
  belongs_to :brigade
  has_many :event_histories, dependent: :destroy

  validates_presence_of :name, :spaces, :responsable_id ,:event_type, 
                        :event_date, :state, :place, :activation_date
  validates_presence_of :spaces, if: Proc.new {|e| e.event_type.has_limit }

  delegate :name, :email, to: :responsable, prefix: true, allow_nil: true

  scope :active, -> { where("state = '#{EVENT_STATES[0]}'") }
  scope :future, -> { where("event_date >= '#{DateTime.now}'").order('event_date asc') }
  scope :city, ->(city_id) { where("city_id = :city_id", city_id: city_id) }
  scope :before, ->(end_time) { where("event_date < :event_date", event_date: Event.format_date(end_time)) }
  scope :after, ->(start_time) { where("event_date > :event_date", event_date: Event.format_date(start_time)) }


  #scopes
  def self.induction(city_id)
    includes("event_type").where("event_types.is_inception = 1 and events.city_id = ?", city_id).references(:event_type)
  end

  def is_active?
    self.state.eql? EVENT_STATES[0]
  end

  def is_open?
    !self.event_type.requires_inception
  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
      id: self.id,
      title: get_title,
      description: self.description || "",
      start: self.event_date,
      end: self.event_date,
      allDay: false,
      recurring: false,
      className: (self.event_type.requires_inception ? self.area.color : self.event_type.name),
      url: Rails.application.routes.url_helpers.event_path(self.id)
    }
  end

  def get_title
    event_name = (self.event_type.requires_inception ? "#{self.event_type.name}: #{self.area.name}" : self.event_type.name)
    @cont = self.spaces- self.used
    if self.event_type.has_limit
      event_name = "#{event_name}\nEvento: #{self.name}\nCupos: #{@cont}"|| ""
    else
      event_name = "#{event_name}\nEvento: #{self.name}"|| ""
    end
    return event_name
  end

end

app/models/event_type.rb
class EventType < ActiveRecord::Base

  #attr_accessible :name, :requires_inception, :is_inception, :has_limit

  validates_presence_of :name

  has_many  :events

end

app/controllers/admin/events_controller.rb
# encoding: UTF-8
class Admin::EventsController < Admin::AdminController

  before_filter :set_menu

  def index
    @events = Event.paginate(:page => params[:page], :per_page => 50).order('event_date desc')
  end

  def new
    @event = Event.new
    render :edit
  end

  def create
    @event = Event.new(event_params) # params[:event])
    if @event.event_date
      @event.event_date = DateTime.new(@event.event_date.year, @event.event_date.month, @event.event_date.day, params[:event_date_hour].to_i, params[:event_date_minute].to_i, 0, 0)
      @event.end_time = Time.new(@event.event_date.year, @event.event_date.month, @event.event_date.day, params[:event_end_time_hour].to_i, params[:event_end_time_minute].to_i, 0, 0)
    end
    #@event.event_date.change({hour: params[:event_date_hour], min: params[:event_date_minute]})
    if @event.brigade_id.present? && @event.brigade.brigade_leader_id.present?
      @event.responsable_id =  @event.brigade.brigade_leader_id
    end
    if @event.save
      flash[:notice] = "Evento #{@event.name} guardado"
      redirect_to admin_events_path and return
    else
      flash[:error] = "Evento #{@event.name} no pudo ser guardado"
      render :edit
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def edit_new
    @event = Event.find(params[:id])
    @event_image = @event.event_images.new
  end

  def destroy_image
    @event_image = EventImage.find(params[:id])
    event_id = @event_image.event_id
    @event_image.destroy
    redirect_to edit_new_admin_event_path(event_id)
  end

  def update
    @event = Event.find(params[:id])
    @event.attributes = event_params # params[:event]
    if @event.event_date
      @event.event_date = DateTime.new(@event.event_date.year, @event.event_date.month, @event.event_date.day, params[:event_date_hour].to_i, params[:event_date_minute].to_i, 0, 0)
      @event.end_time = Time.new(@event.event_date.year, @event.event_date.month, @event.event_date.day, params[:event_end_time_hour].to_i, params[:event_end_time_minute].to_i, 0, 0)
    end
    if @event.brigade_id.present? && @event.brigade.brigade_leader_id.present?
      @event.responsable_id =  @event.brigade.brigade_leader_id
    end
    if @event.save
      flash[:notice] = "Evento #{@event.name} guardado"
      redirect_to admin_events_path and return
    else
      flash[:error] = "Evento #{@event.name} no pudo ser guardado"
      if params[:edit_page_flag]=='edit_new'
        render :edit_new  
      else
        render :edit
      end
    end
  end

  def add_image
    @event = Event.find(params[:id])
    @event_image = @event.event_images.new(params[:event_image])
    if @event_image.save
      flash[:notice] = "Imagen para evento #{@event.name} guardada"
      redirect_to edit_new_admin_event_path(@event.id) and return
    else
      flash[:error] = "Imagen para evento #{@event.name} no pudo ser guardada"
      render :edit_new 
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to admin_events_url
  end

  def responsable_autocomplete
    term = "%#{params[:term].downcase}%"
    user = User.where("lower(first_name) like ? or lower(last_name) like ? or lower(concat(first_name,' ',last_name)) like ?", term, term, term)
    render json: user.collect{|u|  {id: u.to_param, value: u.name}}.to_json
  end

  def entry_list
    @event = Event.find(params[:id])
    @events_users = @event.events_users.includes(:user).paginate(:page => params[:page], :per_page => 50)
    # @users = @event.users.paginate(:page => params[:page], :per_page => 50)
  end

  def remove_participant
    event_user = Event.find(params[:id]).events_users.find_by_user_id(params[:uid])
    if event_user
      event_user.destroy
      render js: "$('#volunteer_#{params[:uid]}').remove();"
    else
      render js: "alert('No se pudo remover al voluntario del evento');"
    end
  end

  def entry_list_to_xlsx
    @event = Event.find(params[:id])
    @events_users = @event.events_users.includes(:user)
    headers['Content-Disposition'] = "attachment; filename=Inscritos_#{@event.name}_#{Date.today.strftime('%Y/%m/%d')}.xlsx"
  end

=begin
  def entry_list_to_csv
    @event = Event.find(params[:id])
    users = @event.users

    csv_string = "Nombre, Email, Cédula, FechaNacimiento\r\n"
    users.each do |user|
      csv_string << "#{user.full_name}, #{user.email}, #{user.indentifier}, #{user.birth_date.strftime("%Y-%m-%d") unless user.birth_date.nil?}\r\n"
    end
    send_data csv_string.encode("UTF-8"), :type => "text/csv; charset=utf-8; header=present", :filename =>
        "inscritos_#{@event.name}_#{Time.now.strftime("%m-%d-%Y")}.csv", :disposition =>
        'attachment'
  end
=end

  def events_filter
    if(params[:event_type_id].present? && params[:start_date].present? && params[:end_date].present?)
      params[:end_date] = (params[:end_date].present? ? DateTime.strptime(params[:end_date], '%Y-%m-%d') : Time.now)
      params[:end_date] = params[:end_date].end_of_day+ 1.hour
      params[:start_date] = (params[:start_date].present? ? DateTime.strptime(params[:start_date], '%Y-%m-%d') : (params[:end_date] - 30.days))
      params[:start_date] = params[:start_date].beginning_of_day
      @events = Event.where('event_date >= ? AND event_date <= ? AND event_type_id = ? ', params[:start_date], params[:end_date], params[:event_type_id]).order('created_at DESC').paginate(per_page: 100, page: params[:page]) 
    elsif(params[:event_type_id].present?)
      @events = Event.where('event_type_id = ? ', params[:event_type_id]).paginate(:page => params[:page], :per_page => 50)
    elsif(params[:start_date].present? && params[:end_date].present?) 
      params[:end_date] = (params[:end_date].present? ? DateTime.strptime(params[:end_date], '%Y-%m-%d') : Time.now)
      params[:end_date] = params[:end_date].end_of_day + 1.hour
      params[:start_date] = (params[:start_date].present? ? DateTime.strptime(params[:start_date], '%Y-%m-%d') : (params[:end_date] - 30.days))
      params[:start_date] = params[:start_date].beginning_of_day
      @events = Event.where('event_date >= ? AND event_date <= ?', params[:start_date], params[:end_date]).order('created_at DESC').paginate(per_page: 100, page: params[:page])
    elsif(!params[:event_type_id].present?)
      @events = Event.paginate(:page => params[:page], :per_page => 50).order('event_date desc')
    end
    respond_to do |format|
      format.html {}
      format.js { render :index }
    end
  end


  private

  def set_menu
    @selected_menu = 'Events'
  end

  def event_params
    params.require(:event).permit(:name, :description, :spaces, :used, :event_type, 
                  :event_type_id, :event_date, :state, :place,  
                  :responsable_id, :city_id, :city, :requires_adult, 
                  :area, :area_id, :role, :activation_date, :brigade_id)
  end

end

app/controllers/events_controller.rb
# encoding: UTF-8
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]

  def show
    @event = Event.find(params[:id])
    # p "@event:#{@event.inspect}:::@event.is_active?:#{@event.is_active?}::#{@event.state}::#{Event::EVENT_STATES[0]}"
    redirect_to root_path and return if !@event || !@event.is_active?
    @next_inductions = Event.induction(@event.city_id).future.limit(2)
  end

  def logged
    show
    render :show
  end

  def join
    @event = Event.find(params[:id])
    redirect_to root_path and return if !@event || !@event.is_active?

    if ((@event.activation_date || @event.created_at) > DateTime.now) # not open to registration yet
      flash[:notice] = "Los registros en línea se abrirán desde: #{(@event.activation_date ? @event.activation_date.strftime("%Y-%m-%d") : @event.created_at.strftime("%d/%m/%Y"))}"
    else
      if @event.event_date < (DateTime.now - 24.hours) # Registration is closed
          flash[:notice] = 'Los registros se deben realizar 24 horas antes del evento'
      else
        if @event.requires_adult && !current_user.is_adult?
          flash[:notice] = 'Este evento require que sea mayor de edad para poder participar'
        else
          if @event.is_open? || current_user.has_induction?
            available = @event.spaces - @event.used
            if @event.event_type.has_limit && available == 0 # no spaces available
              flash[:notice] = 'No hay cupos disponibles para este evento. Por favor revise otros eventos'
            else # spaces available
              @event.users << current_user
              @event.used = @event.users.count
              @event.save
              MessageMailer.joined(@event, current_user).deliver
              MessageMailer.new_register(@event, current_user).deliver
            end
          else
            flash[:notice] = 'Como pre-requisito, debe participar en una induccion antes de poder ser voluntario.'
            @next_inductions = Event.induction(@event.city_id).future.limit(2)
          end
        end
      end
    end
    render :show
  end

  def responsable_autocomplete
    term = "%#{params[:term].downcase}%"
    user = User.where("lower(first_name) like ? or lower(last_name) like ? or lower(concat(first_name,' ',last_name)) like ?", term, term, term)
    render json: user.collect{|u|  {id: u.to_param, value: u.name}}.to_json
  end

end

app/views/admin/events/_events.html.haml
.row
  .col-md-12
    %table.table.table-striped.table-responsive
      %thead
        %tr
          %th Nombre
          %th Lugar
          %th Usados (Espacios)
          %th Fecha
          %th Estado
          %th Listado de inscritos
      %tbody
        - @events.each do |event|
          %tr
            %td
              - if event.event_date <= Time.now.utc+Time.now.utc_offset
                = link_to "#{event.name} (#{event.event_type.name}: #{event.area.name}) (Pasado)", 
                  edit_new_admin_event_path(event.id)
              - else
                = link_to "#{event.name} (#{event.event_type.name}: #{event.area.name})", edit_admin_event_path(event.id)
            / %td #{event.city.name}, #{event.place}
            %td= (event.event_type.has_limit ? "#{event.used} (#{event.spaces})" : "#{event.used} (ilimitado)")
            %td
              Activación: #{(event.activation_date || event.created_at).strftime("%d/%m/%Y")}
              %br/
              Evento: #{event.event_date.strftime("%Y-%m-%d %H:%M")}
            %td= event.state
            %td= link_to "Ver", entry_list_path(event.id)
= page_entries_info @events_new
= will_paginate @events_new

app/views/admin/events/edit.html.haml
.container.admin
  = render 'shared/navigation_admin'
  .row.adform
    = form_for @event, url: (@event.new_record? ? admin_events_path : admin_event_path(@event.id)), method: (@event.new_record? ? 'post' : 'put'), html: {id: 'eventForm'} do |f|
      .chart
        %h3.module_header
          #{(@event.new_record? ? 'Nuevo evento' : "Editar evento")}
      
      .col-lg-6
        .temp_list
          %ul
            %li
              - unless @event.errors.empty?
                .alert.alert-danger.errors
                  = @event.errors.full_messages.join(', ')
            %li
              .row
                .col-lg-3
                  %span Tipo de Evento *
                .col-lg-9
                  = f.select :event_type_id, options_from_collection_for_select(EventType.all, :id, :name, @event.event_type_id), {}, {class: "form-control"}
            %li
              .row
                .col-lg-3
                  %span Ciudad *
                .col-lg-9
                  = f.select :city_id, options_from_collection_for_select(City.all, :id, :name, @event.city_id), {}, {class: "form-control"}
            %li
              .row
                .col-lg-3
                  %span Nombre *
                .col-lg-9
                  = f.text_field :name, size: '150', maxlenght: '150', class: "form-control"
            %li
              .row
                .col-lg-3
                  %span Lugar *
                .col-lg-9
                  = f.text_field :place, size: '250', maxlenght: '250', class: "form-control"

            %li
              .row
                .col-lg-3
                  %span
                    Fecha de
                    %br/
                    activación *
                .col-lg-9
                  = f.text_field :activation_date, size: '5', maxlenght: '5', value: (@event.activation_date.nil? ? '' : (@event.activation_date || @event.created_at).strftime("%d/%m/%Y")), class: 'datepicker date', style: 'padding: 15px;'
            %li
              .row
                .col-lg-3
                  %span
                    Fecha de
                    %br/
                    evento *
                .col-lg-9
                  .row
                    .col-md-12
                      = f.text_field :event_date, size: '5', maxlenght: '5', value: (@event.event_date.nil? ? '' : @event.event_date.strftime("%d/%m/%Y")), class: 'datepicker date', style: 'padding: 15px;'
                    .col-md-3
                      .pull-right
                        Hora inicio:
                    .col-md-9
                      = select_tag :event_date_hour, options_for_select((6..20), (@event.new_record? ? '' : @event.event_date.hour)), style: 'width: 65px;'
                      \-
                      = select_tag :event_date_minute, options_for_select((0..45).step(15), (@event.new_record? ? '' : @event.event_date.min)), style: 'width: 65px;'
                    .col-md-3
                      .pull-right
                        Hora fin:
                    .col-md-9
                      = select_tag :event_end_time_hour, options_for_select((6..24), (@event.new_record? ? '' : @event.end_time.hour)), style: 'width: 65px;'
                      \-
                      = select_tag :event_end_time_minute, options_for_select((0..45).step(15), (@event.new_record? ? '' : @event.end_time.min)), style: 'width: 65px;'

            %li
              .row
                .col-lg-3
                  %span Rol *
                .col-lg-9
                  = f.text_field :role, class: "form-control", size: '250', maxlenght: '250'

            %li
              .row
                .col-lg-3
                  %span Espacios disponibles *
                .col-lg-9
                  = f.select :spaces, options_for_select((0..50), @event.spaces), {}, {class: "form-control", style: "#{('display: none;' if @event.new_record? || !@event.event_type.has_limit)}"}
                  %span#unlimited_text{style: ('display: none;' if !@event.new_record? && @event.event_type.has_limit)} Ilimitado

            %li
              .row
                .col-lg-3
                  %span Brigada
                .col-lg-9
                  = f.select :brigade_id, options_from_collection_for_select(Brigade.all, :id, :name, @event.brigade_id), {include_blank: true}, {class: "form-control"}

            %li
              .row
                .col-lg-3
                  %span Responsable *
                .col-lg-9
                  = f.hidden_field :responsable_id
                  = text_field_tag :responsable_name, @event.responsable_name, class: "form-control", size: '150', maxlenght: '150'

      .col-lg-6
        .chart
          .temp_list
            %ul
              %li
                .row
                  .col-lg-3
                    %span Descripci&oacute;n:
                  .col-lg-9
                    = f.text_area :description, class: "form-control", size: '10x5', style: 'width: 100%;', maxlength: '255'
              
              %li
                .row
                  .col-lg-12
                    %span
                      Requiere ser mayor de edad para participar:
                      = f.check_box :requires_adult, style: 'margin-top: -3px;'
              
              %li
                .row
                  .col-lg-3
                    %span Estado *
                  .col-lg-9
                    = f.select :state, options_for_select(Event::EVENT_STATES, @event.state), {}, {class: "form-control"}
              
              %li
                %i{style: 'font-size: 12px;'} Los campos marcados con * son obligatorios
                %hr/
                .botones
                  = link_to "Guardar", "#", onclick: "$('#eventForm').submit(); return false;", class: 'btn btn-primary btn-inverse'
                  = link_to "Cancelar", admin_events_path, class: 'btn btn-default'
                  - unless @event.new_record?
                    = link_to "Borrar", admin_event_path(@event.id), class: 'btn btn-default', confirm: "Esta seguro que desea borrar el evento:#{@event.name}?", method: 'delete'



- content_for :js_footer do
  :javascript
    $.ajax({async:false});
    $(function() {
      var event_types = {#{EventType.all.collect{|e| "#{e.id}: #{e.has_limit}"}.join(',')}};
      $(".datepicker").datepicker({
        dateFormat: "yy-mm-dd",
        changeMonth: true,
        changeYear: true,
        minDate: "-12M",
        maxDate: "+6M"
      });

      $('#event_event_type_id').on('change', function() {
        if(event_types[$(this).val()]) {
          $('#event_spaces').show();
          $('#unlimited_text').hide();
        } else {
          $('#event_spaces').hide();
          $('#unlimited_text').show();
        }
      });

      $('#responsable_name')
        .bind( "keydown", function(event) {
          //alert(event.keyCode);
          if(event.keyCode === $.ui.keyCode.ENTER && $(this).data("ui-autocomplete").menu.active) {
            event.preventDefault();
          } else if (!(event.keyCode === $.ui.keyCode.TAB)){
            $(this).css("border-color","#D82D2D");
            $("#event_responsable_id").val("");
          }
        })
        .autocomplete({
          source: "#{admin_responsable_autocomplete_path}",
          minLength: 1,
          select: function( event, ui ) {
            if(ui.item) {
              $(this).css("border-color","#44db2f");
              $("#event_responsable_id").val(ui.item.id);
            } else {
              return false;
            }
          }
        })
        .blur(function(){
          if($(this).val() ===""){
            $(this).css("border-color","#D82D2D");
            $("#event_responsable_id").val("");
          }
        });
    });

app/views/admin/events/edit_new.html.haml
.container.admin
  = render 'shared/navigation_admin'
  .row.adform
    .chart
      %h3.module_header Subir imagenes de evento
    .col-lg-12
      .panel-body
        %table.table.table-bordered{style: 'background-color: #fff;'}
          %tr
            %td Tipo de Evento: #{@event.event_type.name}
            %td Ciudad: #{@event.city.name}
          %tr
            %td Nombre: #{@event.name}
            %td Lugar: #{@event.place}
            %td Fecha de activación: #{@event.activation_date.strftime("%d/%m/%Y ")}
          %tr
            %td Fecha de evento: #{@event.event_date.strftime("%d/%m/%Y")}
            %td Hora: #{@event.event_date.strftime("%I:%M")}
            %td Rol: #{@event.role}
          %tr
            %td Responsable: #{@event.responsable_name}
            %td Descripci&oacute;n:: #{@event.description}
            %td Mayores de edad: #{@event.requires_adult ? 'Sí' : 'No'}
          %tr
            %td Estado: #{@event.state}
      .chart
        %h3.module_header Imagenes
    .col-lg-12
      .row
        - @event.event_images.each do |event_image|
          - if !event_image.image_file_name.nil?
            .col-md-3.col-sm-4
              .caja-imagen
                = link_to image_tag(event_image.image.url(:large)), event_image.image.url, target: '_blank'
                = link_to 'X', destroy_image_admin_event_path(event_image.id), confirm: "Are you sure you want to delete image?", method: :delete
    = form_for @event_image, url: add_image_admin_event_path(@event.id), method: :post, html: {id: 'eventForm'} do |f|
      .col-lg-12
        %ul
          %li
            - unless @event_image.errors.empty?
              .alert.alert-danger.errors
                = @event_image.errors.full_messages.join(', ')
        .temp_list
          %ul
            %li
              .row
                .col-lg-3 Agregar imagen:
                .col-lg-3
                  = f.file_field :image
            %li
              .botones
                = link_to "Guardar", "#", onclick: "$('#eventForm').submit(); return false;", class: 'btn btn-primary btn-inverse'
                = link_to "Cancelar", admin_events_path, class: 'btn btn-default'
    

app/views/admin/events/entry_list.html.haml
.container.admin
  = render 'shared/navigation_admin'
  .row
    .col-lg-10
      .chart
        %h3.module_header
          Inscritos para evento '#{@event.name}': 
          %span.count
            #{@events_users.count}
          =# link_to 'Exportar a CSV', entry_list_to_csv_path(@event.id), style: "float:right;", class: 'btn'
          = link_to 'Exportar a Excel', entry_list_to_xlsx_path(format: :xlsx), style: "margin-right:10px;", class: 'btn btn-xs btn-primary pull-right'

        .options
          = page_entries_info @events_users
          = will_paginate @events_users

        %table.table.table-striped
          %tr
            %th Nombre
            %th Correo
            %th Celular
            %th Fecha de Nacimiento
            %th Brigadista
            %th Remover?

          - @events_users.each do |events_user|
            - user = events_user.user
            %tr{id: "volunteer_#{user.id}"}
              %td= user.full_name
              %td= user.email
              %td= user.mobile
              %td= user.birth_date.strftime("%Y-%m-%d") unless user.birth_date.nil?
              %td #{events_user.is_brigadist ? 'Sí' : 'No'}
              %td= link_to 'Remover?', remove_participant_admin_event_path(@event.id, uid: user.id), remote: true, method: :delete, data: { confirm: "Esta seguro que desea eliminar al usuario: '#{user.full_name}'' del evento: '#{@event.name}'"}

app/views/admin/events/index.html.haml
.container.admin
  = render 'shared/navigation_admin'
  .row
    .col-lg-10
      .chart
        %h3.module_header
          Eventos
          %span.count
            #{@events.count}
          %span{style: "float:right;"}=# link_to 'Export to CSV', to_csv_admin_event_path(0)
    .col-lg-2
      %a.my_button{href: new_admin_event_path, style: 'margin-top: 30px;'}
        Nuevo Evento        
    .col-lg-12
      .well
        .row
          .col-lg-5
          .col-lg-2
            Busqueda:
            %br
          .col-lg-5
        .row
        .row
          = form_tag events_filter_path, method: 'get', remote: true do
            .col-sm-2
              .input-group.input-group-sm
                Fecha Inicial
                = text_field_tag :start_date, "", class: 'form-control datepicker date', placeholder:'Inicial'
            .col-sm-2
              .input-group.input-group-sm
                Fecha Final
                = text_field_tag :end_date, "", class: 'form-control datepicker date', placeholder:'Final'
            .col-sm-3
              %label.pull-left 
              Brigada
              %br
              = select_tag :event_type_id, options_from_collection_for_select(EventType.all, :id, :name), {include_blank: true}
            .col-sm-1.pull-left
              %button.btn.btn-succes{type: "submit", value: "Search",style:"margin-top:15px"}
                %i.glyphicon.glyphicon-search
            .col-md-1
            .col-md-1
        %br
        .report-content
          = render 'events' 

- content_for :js_footer do
  :javascript
    $(function() {
      $('input.datepicker').datepicker({
        dateFormat: "yy-mm-dd",
        changeMonth: true,
        changeYear: true,
        minDate: "-12M",
        maxDate: "+6M"
      });
    });

app/views/admin/events/index.js.haml
$('.report-content').html("#{j render 'events'}");