config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/fb_channel' => 'home#fb_channel', :as => 'fb_channel'

  get "info/historianew"

  get 'info/' => "info#index", as: :info

  get 'event/:id' => 'events#show', as: :event
  get 'event/:id/logged' => 'events#logged', as: :logged
  get 'join/:id' => 'events#join', as: :join

  get 'calendar' => 'home#calendar', as: :calendar

  get 'event/entry_list/:id' => 'admin/events#entry_list', as: :entry_list

  get 'event/entry_list_to_xlsx/:id' => 'admin/events#entry_list_to_xlsx', as: :entry_list_to_xlsx

  get 'info/send_mail' => 'info#send_mail', as: :info_send_mail
  
  get 'responsable_autocomplete' => 'events#responsable_autocomplete'

  get 'brigades/dashboard' => 'brigades#dashboard', as: :brigades_dash
  get 'brigades/brigades' => 'brigades#index', as: :brigades_index
  get 'brigades/:id/view_event' => 'brigades#view_event', as: :view_event
  get 'brigades/:id/view_brigade' => 'brigades#view_brigade', as: :view_brigade
  post 'brigades/:id/add_brigadist' => 'brigades#add_brigadist', as: :add_brigadist
  post 'brigades/:id/remove_brigadist' => 'brigades#remove_brigadist', as: :remove_brigadist
  get 'admin/volunteers/volunteer_filter' => 'admin/volunteers#volunteer_filter', as: :volunteer_filter
  get 'admin/children/child_filter' => 'admin/children#child_filter', as: :child_filter
  get 'admin/polls/poll_filter' => 'admin/polls#poll_filter', as: :poll_filter
  get 'admin/events/events_filter' => 'admin/events#events_filter', as: :events_filter
  get 'admin/users/users_filter' => 'admin/users#users_filter', as: :users_filter
  
  namespace :admin do
    resource :dash

    resources :users do
      member do
        get :login_as, :resend_activation, :to_csv
        post :make_admin
      end
      collection do
        get :chart_data
      end
    end

    resources :volunteers do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv
      end
    end
    
    resources :children do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv

      end

    end

    resources :polls do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv
        post :from_xlsx
      end
    end

    resources :brigades
    resources :events do
      member do
        get :edit_new
        post :add_image
        delete :destroy_image, :remove_participant
      end
    end
    get 'responsable_autocomplete' => 'events#responsable_autocomplete'

    resources :hospitals do 

    end

  end

  get '/return_to_admin' => 'home#return_to_admin', :as => :return_to_admin

end

app/views/shared/_facebook_init.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : "<%= FB_APP_ID -%>", // App ID
      channelUrl : '//<%= "#{request.host}:#{request.port}" -%>/fb_channel', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true,  // parse XFBML
      frictionlessRequests: true //dialog request
    });
  };

  // Load the SDK Asynchronously
  (function(d){
    var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement('script'); js.id = id; js.async = true;
    js.src = "//connect.facebook.net/en_US/all.js";
    ref.parentNode.insertBefore(js, ref);
  }(document));

  function publishToFeed(link, image_url, title, name) {
    var title_msg = title;
    if (title==undefined || title == null){
      title_msg = 'Shared from Sitebootstrapper!';
    }
    var obj = {
      method: 'feed',
      link: link,
      picture: image_url,
      name: title_msg,
      caption: link,
      description: name
    };
    function callback(response) {
      // alert('It worked');
    }
    FB.ui(obj, callback);
  }
</script>

app/views/shared/_footer.html.haml
/
  %p ¿No quieres participar aún? Entonces pasa la voz:
  = render 'shared/social_buttons'

.footer.container

  .row
    .col-lg-12
      %p
        © 2014 -
        = link_to "Historia de la colaboración", "/info", target: "_blank"

app/views/shared/_header.html.haml
.jumbotron.imagen_portada{style: 'height: 0px; padding: 0px;'}
  /
    .logo_org
    .frases
      #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
        .carousel-inner
          .item.active
            "Frase número uno."
            .autor
              \- Autor de la frase
          .item.active
            "Con pasión por la tecnología."
            .autor
              \- Autor de la frase
          .item.active
            "La obra humana más bella es la de ser útil al prójimo."
            .autor
              \- Sófocles

  %nav.menu_portada{role: "navigation"}
    =render "shared/navigation_public"

app/views/shared/_navigation_admin.html.haml
.header
  .header_top
    .menu
      %a.toggleMenu{href: "#"}
        = image_tag("nav.png")
      %ul.nav
        %li
          = link_to root_path do
            Calendario
        %li{class: ('active' if @selected_menu == 'Dash')}
          = link_to admin_dash_path do
            %i>
              = image_tag("statistics.png")
            Tablero

        %li{class: ('active' if @selected_menu == 'Users')}
          = link_to admin_users_path do
            %i>
              = image_tag("user.png")
            Usuarios

        %li{class: ('active' if @selected_menu == 'Volunteers')}
          = link_to admin_volunteers_path do
            %i>
              = image_tag("likes.png")
            Voluntarios
            %span.messages
              = @volunteersCount

        %li{class: ('active' if @selected_menu == 'Events')}
          = link_to admin_events_path do
            %i>
              = image_tag("events.png")
            Eventos
            %span.messages
              = @eventsCount
        %li{class: ('active' if @selected_menu == 'Brigades')}
          = link_to admin_brigades_path do
            %i>
              = image_tag("follow_user.png")
            Brigadas
            %span.messages
              = @brigadesCount
        %li{class: ('active' if @selected_menu == 'Children')}
          = link_to admin_children_path do
            %i>
              = image_tag("follow_user.png")
            Niños
            %span.messages
              = @childrenCount
        

        .clear

        %li{class: ('active' if @selected_menu == 'Polls')}
          = link_to admin_polls_path do
            %i>
              = image_tag("follow_user.png")
            Encuestas
            %span.messages
              = @pollsCount

        %li{class: ('active' if @selected_menu == 'Hospitals')}
          = link_to admin_hospitals_path do
            %i>
              %img{alt: "", src: "/assets/follow_user.png"}/
            Hospitales
            %span.messages
              = @hospitalsCount

    .profile_details
      .dropdown
        %button#dLabel{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button", class: 'btn btn-default'}
          #{current_user.full_name}
          %span.caret
        %ul.dropdown-menu{"aria-labelledby" => "dLabel"}
          %li
            = link_to 'Perfil', edit_user_registration_path, :class => ('active' if controller_name == 'registrations')
            
          %li= link_to 'Salir', destroy_user_session_path, :method => 'delete'
    -#
      .profile_details
        #loginContainer
          %a#loginButton
            %span Yo
          #loginBox
            %form#loginForm
              %fieldset#body
                .user-info
                  %h4
                    Hola,
                    %a{href: "#"} 
                  %ul.dropdown-menu{"aria-labelledby" => "dLabel"}
                    %li
                      = image_tag(current_user.photo.url, :size => "40x40", :alt => "")
                      = link_to current_user.full_name, edit_user_registration_path, :class => ('active' if controller_name == 'registrations')
                      

                    %li= link_to 'Salir', destroy_user_session_path, :method => 'delete'

                    .clear
        .profile_img
          %a{href: "#"}
            = image_tag("profile_img40x40.jpg")
        .clear
    .clear

app/views/shared/_navigation_leader.html.haml
.header
  .header_top
    .menu
      %a.toggleMenu{href: "#"}
        = image_tag("nav.png")
      %ul.nav
        %li
          = link_to root_path do
            Calendario
        - if current_user.is_event_responsable?
          %li{class: ('active' if @selected_menu == 'Dash')}
            = link_to brigades_dash_path do
              %i>
                = image_tag("statistics.png")
              Eventos

        - if current_user.is_brigade_leader?
          %li{class: ('active' if @selected_menu == 'Dash')}
            = link_to brigades_index_path do
              %i>
                = image_tag("statistics.png")
              Brigadas
            
        .clear
      %script{src: "/assets/responsive-nav.js", type: "text/javascript"}
    .profile_details
      #loginContainer
        %a#loginButton
          %span Yo
        #loginBox
          %form#loginForm
            %fieldset#body
              .user-info
                %h4
                  Hello,
                  %a{href: "#"} Username
                %ul
                  %li
                    = image_tag(current_user.photo.url, :size => "40x40", :alt => "")
                    = link_to current_user.full_name, edit_user_registration_path, :class => ('active' if controller_name == 'registrations')
                    

                  %li= link_to 'Salir', destroy_user_session_path, :method => 'delete'

                  .clear
      .profile_img
        %a{href: "#"}
          = image_tag("profile_img40x40.jpg")
      .clear
    .clear

app/views/shared/_navigation_public.html.haml
.menu_usuario.btn-group{style: 'margin-top: 20px;'}
  
  - if user_signed_in?
    = link_to edit_user_registration_path, :class => (controller_name == 'registrations' ? 'active btn btn-default' : 'btn btn-default') do
      = image_tag(current_user.photo.url, :size => "15x15", :alt => "")
      #{current_user.full_name}
    - if request.fullpath != "/"
      = link_to 'Calendario', "/", class: 'btn btn-info', type: 'button'
    - if(session["admin_user_id"])
      = link_to 'Administrar', return_to_admin_path, class: 'btn btn-default', type: 'button'
    - else
      - if current_user.is_admin?
        = link_to 'Administrar', admin_dash_path, type: "button", target: '_blank', class: ((request.fullpath.starts_with? '/admin') ? 'active btn btn-default' : 'btn btn-default')
    - if current_user.is_brigade_leader? || current_user.is_event_responsable?
      = link_to 'Gestionar eventos', (current_user.is_brigade_leader? ? brigades_index_path : brigades_dash_path), type: "button", target: '_blank', class: ((request.fullpath.starts_with? '/brigades') ? 'active btn btn-default' : 'btn btn-default')
    = link_to 'Salir', destroy_user_session_path, :method => 'delete', class: 'btn btn-default'
  
  - else
    = link_to 'Ingresar', new_session_path(:user), class: 'btn btn-primary', type: 'button'
    
    - if request.fullpath != "/"
      = link_to 'Calendario', "/", class: 'btn btn-info', type: 'button'
    
    = link_to 'Registro', new_registration_path(:user), class: 'btn btn-default', type: 'button'
    = link_to 'Sobre el sistema', '/info', class: 'btn btn-default', type: 'button', target: '_blank'

app/views/shared/_social_buttons.html.haml
#social_buttons
  %hr/
  %p Ayudanos a pasar la voz:
  %span.facebook{style: 'padding-right: 40px;'}
    - if defined? FB_APP_ID
      %a{:class => "FB_share", :type => "icon_link", :href => '#', :onclick => "publishToFeed('#{request.url}','#{request.base_url}#{path_to_image('SBv2.png')}','Sitebootstrapper!','It is very simple. To post to FB.');"}
        = image_tag'facebook1.png', style: 'position: relative; top: 4px;'
    - else
      To share on FB, follow instructions.

  %span.twitter
    %a.twitter-share-button{"data-count" => "horizontal", "data-text" => 'It is very simple. To post to Twitter.', "data-via" => "SitebootstrapperV2", "data-url" => request.url, :href => "http://twitter.com/share", :target => "_blank"} Tweet
    :javascript
      !function(d,s,id){
        var js,fjs=d.getElementsByTagName(s)[0];
        if(!d.getElementById(id)){
          js=d.createElement(s);js.id=id;
          js.src="https://platform.twitter.com/widgets.js";
          fjs.parentNode.insertBefore(js,fjs);
        }
      }(document,"script","twitter-wjs");

  -#
    %span.pinterest
      %a.pin-it-button{"count-layout" => "horizontal", :href => "http://pinterest.com/pin/create/button/?url=#{CGI.escape(request.url)}&media=#{CGI.escape("#{request.base_url}#{path_to_image('SBv2.png')}")}&description=#{CGI.escape('It is very simple. To post to Pinterest.')}", :target => "_blank"}
        %img(border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It")
      = javascript_include_tag "//assets.pinterest.com/js/pinit.js"

  %span.google_plus
    %a.g-plus{"data-action" => "share", "data-annotation" => "bubble", "data-href" => request.url}
    :javascript
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();