config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/fb_channel' => 'home#fb_channel', :as => 'fb_channel'

  get "info/historianew"

  get 'info/' => "info#index", as: :info

  get 'event/:id' => 'events#show', as: :event
  get 'event/:id/logged' => 'events#logged', as: :logged
  get 'join/:id' => 'events#join', as: :join

  get 'calendar' => 'home#calendar', as: :calendar

  get 'event/entry_list/:id' => 'admin/events#entry_list', as: :entry_list

  get 'event/entry_list_to_xlsx/:id' => 'admin/events#entry_list_to_xlsx', as: :entry_list_to_xlsx

  get 'info/send_mail' => 'info#send_mail', as: :info_send_mail
  
  get 'responsable_autocomplete' => 'events#responsable_autocomplete'

  get 'brigades/dashboard' => 'brigades#dashboard', as: :brigades_dash
  get 'brigades/brigades' => 'brigades#index', as: :brigades_index
  get 'brigades/:id/view_event' => 'brigades#view_event', as: :view_event
  get 'brigades/:id/view_brigade' => 'brigades#view_brigade', as: :view_brigade
  post 'brigades/:id/add_brigadist' => 'brigades#add_brigadist', as: :add_brigadist
  post 'brigades/:id/remove_brigadist' => 'brigades#remove_brigadist', as: :remove_brigadist
  get 'admin/volunteers/volunteer_filter' => 'admin/volunteers#volunteer_filter', as: :volunteer_filter
  get 'admin/children/child_filter' => 'admin/children#child_filter', as: :child_filter
  get 'admin/polls/poll_filter' => 'admin/polls#poll_filter', as: :poll_filter
  get 'admin/events/events_filter' => 'admin/events#events_filter', as: :events_filter
  get 'admin/users/users_filter' => 'admin/users#users_filter', as: :users_filter
  
  namespace :admin do
    resource :dash

    resources :users do
      member do
        get :login_as, :resend_activation, :to_csv
        post :make_admin
      end
      collection do
        get :chart_data
      end
    end

    resources :volunteers do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv
      end
    end
    
    resources :children do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv

      end

    end

    resources :polls do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv
        post :from_xlsx
      end
    end

    resources :brigades
    resources :events do
      member do
        get :edit_new
        post :add_image
        delete :destroy_image, :remove_participant
      end
    end
    get 'responsable_autocomplete' => 'events#responsable_autocomplete'

    resources :hospitals do 

    end

  end

  get '/return_to_admin' => 'home#return_to_admin', :as => :return_to_admin

end

app/models/event.rb
class Event < ActiveRecord::Base

  include ActionView::Helpers

  EVENT_TYPES = ['Inducción', 'Voluntariado']
  EVENT_STATES = ['Activo', 'Inactivo']
=begin
  attr_accessible :name, :description, :spaces, :used, :event_type, 
                  :event_type_id, :event_date, :state, :place,  
                  :responsable_id, :city_id, :city, :requires_adult, 
                  :area, :area_id, :role, :activation_date, :brigade_id
=end

  has_many :events_users, dependent: :destroy
  has_many :users, through: :events_users
  has_many :event_images, dependent: :destroy
  belongs_to :responsable, class_name: 'User'
  belongs_to :city
  belongs_to :area
  belongs_to :event_type
  belongs_to :brigade
  has_many :event_histories, dependent: :destroy

  validates_presence_of :name, :spaces, :responsable_id ,:event_type, 
                        :event_date, :state, :place, :activation_date
  validates_presence_of :spaces, if: Proc.new {|e| e.event_type.has_limit }

  delegate :name, :email, to: :responsable, prefix: true, allow_nil: true

  scope :active, -> { where("state = '#{EVENT_STATES[0]}'") }
  scope :future, -> { where("event_date >= '#{DateTime.now}'").order('event_date asc') }
  scope :city, ->(city_id) { where("city_id = :city_id", city_id: city_id) }
  scope :before, ->(end_time) { where("event_date < :event_date", event_date: Event.format_date(end_time)) }
  scope :after, ->(start_time) { where("event_date > :event_date", event_date: Event.format_date(start_time)) }


  #scopes
  def self.induction(city_id)
    includes("event_type").where("event_types.is_inception = 1 and events.city_id = ?", city_id).references(:event_type)
  end

  def is_active?
    self.state.eql? EVENT_STATES[0]
  end

  def is_open?
    !self.event_type.requires_inception
  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
      id: self.id,
      title: get_title,
      description: self.description || "",
      start: self.event_date,
      end: self.event_date,
      allDay: false,
      recurring: false,
      className: (self.event_type.requires_inception ? self.area.color : self.event_type.name),
      url: Rails.application.routes.url_helpers.event_path(self.id)
    }
  end

  def get_title
    event_name = (self.event_type.requires_inception ? "#{self.event_type.name}: #{self.area.name}" : self.event_type.name)
    @cont = self.spaces- self.used
    if self.event_type.has_limit
      event_name = "#{event_name}\nEvento: #{self.name}\nCupos: #{@cont}"|| ""
    else
      event_name = "#{event_name}\nEvento: #{self.name}"|| ""
    end
    return event_name
  end

end

app/models/event_type.rb
class EventType < ActiveRecord::Base

  #attr_accessible :name, :requires_inception, :is_inception, :has_limit

  validates_presence_of :name

  has_many  :events

end

app/controllers/admin/events_controller.rb
# encoding: UTF-8
class Admin::EventsController < Admin::AdminController

  before_filter :set_menu

  def index
    @events = Event.paginate(:page => params[:page], :per_page => 50).order('event_date desc')
  end

  def new
    @event = Event.new
    render :edit
  end

  def create
    @event = Event.new(event_params) # params[:event])
    if @event.event_date
      @event.event_date = DateTime.new(@event.event_date.year, @event.event_date.month, @event.event_date.day, params[:event_date_hour].to_i, params[:event_date_minute].to_i, 0, 0)
      @event.end_time = Time.new(@event.event_date.year, @event.event_date.month, @event.event_date.day, params[:event_end_time_hour].to_i, params[:event_end_time_minute].to_i, 0, 0)
    end
    #@event.event_date.change({hour: params[:event_date_hour], min: params[:event_date_minute]})
    if @event.brigade_id.present? && @event.brigade.brigade_leader_id.present?
      @event.responsable_id =  @event.brigade.brigade_leader_id
    end
    if @event.save
      flash[:notice] = "Evento #{@event.name} guardado"
      redirect_to admin_events_path and return
    else
      flash[:error] = "Evento #{@event.name} no pudo ser guardado"
      render :edit
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def edit_new
    @event = Event.find(params[:id])
    @event_image = @event.event_images.new
  end

  def destroy_image
    @event_image = EventImage.find(params[:id])
    event_id = @event_image.event_id
    @event_image.destroy
    redirect_to edit_new_admin_event_path(event_id)
  end

  def update
    @event = Event.find(params[:id])
    @event.attributes = event_params # params[:event]
    if @event.event_date
      @event.event_date = DateTime.new(@event.event_date.year, @event.event_date.month, @event.event_date.day, params[:event_date_hour].to_i, params[:event_date_minute].to_i, 0, 0)
      @event.end_time = Time.new(@event.event_date.year, @event.event_date.month, @event.event_date.day, params[:event_end_time_hour].to_i, params[:event_end_time_minute].to_i, 0, 0)
    end
    if @event.brigade_id.present? && @event.brigade.brigade_leader_id.present?
      @event.responsable_id =  @event.brigade.brigade_leader_id
    end
    if @event.save
      flash[:notice] = "Evento #{@event.name} guardado"
      redirect_to admin_events_path and return
    else
      flash[:error] = "Evento #{@event.name} no pudo ser guardado"
      if params[:edit_page_flag]=='edit_new'
        render :edit_new  
      else
        render :edit
      end
    end
  end

  def add_image
    @event = Event.find(params[:id])
    @event_image = @event.event_images.new(params[:event_image])
    if @event_image.save
      flash[:notice] = "Imagen para evento #{@event.name} guardada"
      redirect_to edit_new_admin_event_path(@event.id) and return
    else
      flash[:error] = "Imagen para evento #{@event.name} no pudo ser guardada"
      render :edit_new 
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to admin_events_url
  end

  def responsable_autocomplete
    term = "%#{params[:term].downcase}%"
    user = User.where("lower(first_name) like ? or lower(last_name) like ? or lower(concat(first_name,' ',last_name)) like ?", term, term, term)
    render json: user.collect{|u|  {id: u.to_param, value: u.name}}.to_json
  end

  def entry_list
    @event = Event.find(params[:id])
    @events_users = @event.events_users.includes(:user).paginate(:page => params[:page], :per_page => 50)
    # @users = @event.users.paginate(:page => params[:page], :per_page => 50)
  end

  def remove_participant
    event_user = Event.find(params[:id]).events_users.find_by_user_id(params[:uid])
    if event_user
      event_user.destroy
      render js: "$('#volunteer_#{params[:uid]}').remove();"
    else
      render js: "alert('No se pudo remover al voluntario del evento');"
    end
  end

  def entry_list_to_xlsx
    @event = Event.find(params[:id])
    @events_users = @event.events_users.includes(:user)
    headers['Content-Disposition'] = "attachment; filename=Inscritos_#{@event.name}_#{Date.today.strftime('%Y/%m/%d')}.xlsx"
  end

=begin
  def entry_list_to_csv
    @event = Event.find(params[:id])
    users = @event.users

    csv_string = "Nombre, Email, Cédula, FechaNacimiento\r\n"
    users.each do |user|
      csv_string << "#{user.full_name}, #{user.email}, #{user.indentifier}, #{user.birth_date.strftime("%Y-%m-%d") unless user.birth_date.nil?}\r\n"
    end
    send_data csv_string.encode("UTF-8"), :type => "text/csv; charset=utf-8; header=present", :filename =>
        "inscritos_#{@event.name}_#{Time.now.strftime("%m-%d-%Y")}.csv", :disposition =>
        'attachment'
  end
=end

  def events_filter
    if(params[:event_type_id].present? && params[:start_date].present? && params[:end_date].present?)
      params[:end_date] = (params[:end_date].present? ? DateTime.strptime(params[:end_date], '%Y-%m-%d') : Time.now)
      params[:end_date] = params[:end_date].end_of_day+ 1.hour
      params[:start_date] = (params[:start_date].present? ? DateTime.strptime(params[:start_date], '%Y-%m-%d') : (params[:end_date] - 30.days))
      params[:start_date] = params[:start_date].beginning_of_day
      @events = Event.where('event_date >= ? AND event_date <= ? AND event_type_id = ? ', params[:start_date], params[:end_date], params[:event_type_id]).order('created_at DESC').paginate(per_page: 100, page: params[:page]) 
    elsif(params[:event_type_id].present?)
      @events = Event.where('event_type_id = ? ', params[:event_type_id]).paginate(:page => params[:page], :per_page => 50)
    elsif(params[:start_date].present? && params[:end_date].present?) 
      params[:end_date] = (params[:end_date].present? ? DateTime.strptime(params[:end_date], '%Y-%m-%d') : Time.now)
      params[:end_date] = params[:end_date].end_of_day + 1.hour
      params[:start_date] = (params[:start_date].present? ? DateTime.strptime(params[:start_date], '%Y-%m-%d') : (params[:end_date] - 30.days))
      params[:start_date] = params[:start_date].beginning_of_day
      @events = Event.where('event_date >= ? AND event_date <= ?', params[:start_date], params[:end_date]).order('created_at DESC').paginate(per_page: 100, page: params[:page])
    elsif(!params[:event_type_id].present?)
      @events = Event.paginate(:page => params[:page], :per_page => 50).order('event_date desc')
    end
    respond_to do |format|
      format.html {}
      format.js { render :index }
    end
  end


  private

  def set_menu
    @selected_menu = 'Events'
  end

  def event_params
    params.require(:event).permit(:name, :description, :spaces, :used, :event_type, 
                  :event_type_id, :event_date, :state, :place,  
                  :responsable_id, :city_id, :city, :requires_adult, 
                  :area, :area_id, :role, :activation_date, :brigade_id)
  end

end

app/controllers/events_controller.rb
# encoding: UTF-8
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]

  def show
    @event = Event.find(params[:id])
    # p "@event:#{@event.inspect}:::@event.is_active?:#{@event.is_active?}::#{@event.state}::#{Event::EVENT_STATES[0]}"
    redirect_to root_path and return if !@event || !@event.is_active?
    @next_inductions = Event.induction(@event.city_id).future.limit(2)
  end

  def logged
    show
    render :show
  end

  def join
    @event = Event.find(params[:id])
    redirect_to root_path and return if !@event || !@event.is_active?

    if ((@event.activation_date || @event.created_at) > DateTime.now) # not open to registration yet
      flash[:notice] = "Los registros en línea se abrirán desde: #{(@event.activation_date ? @event.activation_date.strftime("%Y-%m-%d") : @event.created_at.strftime("%d/%m/%Y"))}"
    else
      if @event.event_date < (DateTime.now - 24.hours) # Registration is closed
          flash[:notice] = 'Los registros se deben realizar 24 horas antes del evento'
      else
        if @event.requires_adult && !current_user.is_adult?
          flash[:notice] = 'Este evento require que sea mayor de edad para poder participar'
        else
          if @event.is_open? || current_user.has_induction?
            available = @event.spaces - @event.used
            if @event.event_type.has_limit && available == 0 # no spaces available
              flash[:notice] = 'No hay cupos disponibles para este evento. Por favor revise otros eventos'
            else # spaces available
              @event.users << current_user
              @event.used = @event.users.count
              @event.save
              MessageMailer.joined(@event, current_user).deliver
              MessageMailer.new_register(@event, current_user).deliver
            end
          else
            flash[:notice] = 'Como pre-requisito, debe participar en una induccion antes de poder ser voluntario.'
            @next_inductions = Event.induction(@event.city_id).future.limit(2)
          end
        end
      end
    end
    render :show
  end

  def responsable_autocomplete
    term = "%#{params[:term].downcase}%"
    user = User.where("lower(first_name) like ? or lower(last_name) like ? or lower(concat(first_name,' ',last_name)) like ?", term, term, term)
    render json: user.collect{|u|  {id: u.to_param, value: u.name}}.to_json
  end

end

app/views/events/show.html.haml
= render 'shared/header'

.container.detalle_evento
  .row
    .col-lg-12
      .page-header
        %h1 #{@event.name}
  .row
    .col-lg-4.col-md-4.col-sm-4
      %p
        %span.glyphicon.glyphicon-home
        Lugar:
        %br/
        %br/
        %strong #{@event.place}
      %hr/
      %p
        %span.glyphicon.glyphicon-calendar
        Cuándo:
        %br/
        %br/
        %strong #{@event.event_date.strftime("%Y-%m-%d")}
        %br/
        %strong Inicio: #{@event.event_date.strftime("%H:%M")}
        %br/
        %strong Fin: #{@event.end_time.strftime("%H:%M")}
      %hr/
      %p
        %span.glyphicon.glyphicon-user
        Rol del voluntario:
        %br/
        %br/
        %strong #{@event.role}
      - if @event.event_type.requires_inception
        %hr/
        %p
          %span.glyphicon.glyphicon-list-alt
          Área de intervención:
          %br/
          %br/
          %strong #{@event.area.name}

    
    .col-lg-8.col-md-8.col-sm-8
      - if ((@event.activation_date || @event.created_at) > DateTime.now) # not open to registration yet
        .alert.alert-warning
          Los registros en línea se abrirán desde:
          #{(@event.activation_date || @event.created_at).strftime("%d/%m/%Y")}
          %br/
          Te esperamos!
      - else
        - if @event.event_date < (DateTime.now - 24.hours) # Registration is closed
          .alert.alert-warning
            Los registros se deben realizar 24 horas antes del evento
        - else # registration open
          - if current_user # user is logged in
            - if @event.requires_adult && !current_user.is_adult?
              Este evento require que sea mayor de edad para poder participar
            - else # event does not require adult or user is adult
              - if @event.users.include? current_user # Already has a volunteer spot for this event
                Usted ya tiene un cupo como voluntario, para este evento
              - else
                - if @event.is_open? || current_user.has_induction? # already has induction
                  - if !@event.brigade_id.present? || @event.brigade_id == current_user.brigade_id
                    - if @event.event_type.has_limit
                      - available = @event.spaces - @event.used
                      - if available == 0 # no spaces available
                        %div
                          No hay cupos disponibles para este evento.
                          Por favor revise
                          = link_to 'otros eventos', root_path
                      - else # spaces available
                        %div
                          Cupos disponibles: #{available}
                          %div
                            %br/
                            = link_to 'Participar en el evento', join_path(@event.id), data: { confirm: "Estas Seguro?" }, class: 'btn btn-primary'
                            %br/
                    - else
                      %div
                        Cupos disponibles
                        %div
                          %br/
                          = link_to 'Participar en el evento', join_path(@event.id), data: { confirm: "Estas Seguro?" }, class: 'btn btn-primary'
                          %br/
                  - else
                    Esta es una actividad para la brigada "#{@event.brigade.name}"

                - else # doesn't have induction yet
                  Como pre-requisito, debe participar en una induccion antes de poder ser voluntario.
                  %br
                  Siguientes inducciones:
                  - @next_inductions.each do |induction|
                    %br/
                    = link_to "#{induction.place} (#{induction.event_date.strftime("%Y-%m-%d %H:%M")})", event_path(induction.id)
          - else # not logged in
            Necesita
            =# link_to 'Registrarse', # new_registration_path(:user)
            = link_to 'Ingresar', logged_path(@event.id) #new_session_path(:user)
            al sistema para participar en el evento.
      %div 
        %br/
        #{@event.description}

  =# render 'shared/social_buttons'