config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/fb_channel' => 'home#fb_channel', :as => 'fb_channel'

  get "info/historianew"

  get 'info/' => "info#index", as: :info

  get 'event/:id' => 'events#show', as: :event
  get 'event/:id/logged' => 'events#logged', as: :logged
  get 'join/:id' => 'events#join', as: :join

  get 'calendar' => 'home#calendar', as: :calendar

  get 'event/entry_list/:id' => 'admin/events#entry_list', as: :entry_list

  get 'event/entry_list_to_xlsx/:id' => 'admin/events#entry_list_to_xlsx', as: :entry_list_to_xlsx

  get 'info/send_mail' => 'info#send_mail', as: :info_send_mail
  
  get 'responsable_autocomplete' => 'events#responsable_autocomplete'

  get 'brigades/dashboard' => 'brigades#dashboard', as: :brigades_dash
  get 'brigades/brigades' => 'brigades#index', as: :brigades_index
  get 'brigades/:id/view_event' => 'brigades#view_event', as: :view_event
  get 'brigades/:id/view_brigade' => 'brigades#view_brigade', as: :view_brigade
  post 'brigades/:id/add_brigadist' => 'brigades#add_brigadist', as: :add_brigadist
  post 'brigades/:id/remove_brigadist' => 'brigades#remove_brigadist', as: :remove_brigadist
  get 'admin/volunteers/volunteer_filter' => 'admin/volunteers#volunteer_filter', as: :volunteer_filter
  get 'admin/children/child_filter' => 'admin/children#child_filter', as: :child_filter
  get 'admin/polls/poll_filter' => 'admin/polls#poll_filter', as: :poll_filter
  get 'admin/events/events_filter' => 'admin/events#events_filter', as: :events_filter
  get 'admin/users/users_filter' => 'admin/users#users_filter', as: :users_filter
  
  namespace :admin do
    resource :dash

    resources :users do
      member do
        get :login_as, :resend_activation, :to_csv
        post :make_admin
      end
      collection do
        get :chart_data
      end
    end

    resources :volunteers do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv
      end
    end
    
    resources :children do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv

      end

    end

    resources :polls do
      member do
        post :activate
      end
      collection do
        get :to_xlsx #, :to_csv
        post :from_xlsx
      end
    end

    resources :brigades
    resources :events do
      member do
        get :edit_new
        post :add_image
        delete :destroy_image, :remove_participant
      end
    end
    get 'responsable_autocomplete' => 'events#responsable_autocomplete'

    resources :hospitals do 

    end

  end

  get '/return_to_admin' => 'home#return_to_admin', :as => :return_to_admin

end

app/models/user.rb
#require Sitebootstrapperv2::Engine.root.join('app', 'models', 'user')
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, omniauth_providers: [:twitter, :facebook, :google_oauth2]


  has_many :authentications, dependent: :destroy

  # attr_accessible :tos, :has_induction, :birth_date, :indentifier, :contact_me, :has_institution_induction, :mobile, :motivation, :brigade, :brigade_id, :city_id, :city

  validates_acceptance_of :tos, :message => 'deben ser aceptados'
  validates_presence_of :birth_date, :mobile
  validates :indentifier, uniqueness: true, presence: true

  has_many :events_users, dependent: :destroy
  has_many :events, through: :events_users
  # has_and_belongs_to_many :events
  
  belongs_to :brigade
  belongs_to :city

  before_create :set_first_admin
  before_save :activate

  has_attached_file :photo, {
      url: "/system/:class/:attachment/:id/:style_:basename.:extension",
      path: ":rails_root/public/system/:class/:attachment/:id/:style_:basename.:extension",
      styles: {
          thumbnail: "60x60>",
          original: "250x250>"
      },
      default_url: "/assets/default_user.png"
  }
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  

  def status
    active_for_authentication? ? 'active' : 'pending'
  end

  def full_name
    return "#{first_name} #{last_name}" if !first_name.blank? and !last_name.blank?
    return first_name if !first_name.blank?
    return last_name if !last_name.blank?
    return email if email
    ''
  end

  def password_required?
    (authentications.empty? && !persisted?) || !password.nil? || !password_confirmation.nil?
  end

  def email_required?
    authentications.empty?
  end

  def set_photo_from_url(image_url)
    if !image_url.blank? || self.photo_file_name.blank? || self.photo_file_name == 'default_user.png'
      begin
        io = open(URI.parse(image_url))
        def io.original_filename; base_uri.path.split('/').last end
        if !io.original_filename.blank?
          self.photo = io
        end
      rescue Exception => ex
        logger.error("ERROR ERROR ERROR ::: #{ex.message}")
      end
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.omniauth"]
        user.apply_omniauth(data)
      end
    end
  end

  def is_admin?
    is_admin
  end

  def has_induction?
    self.has_induction
  end

  def is_adult?
    (self.birth_date.nil? ? false : 18.years.ago >= self.birth_date)
  end
 
  def is_brigade_leader?
    return Brigade.where(brigade_leader_id: self.id).count > 0
  end
 
  def is_event_responsable?
    return Event.where(responsable_id: self.id).count > 0
  end

  def name
    full_name
  end

  def profile_not_complete?
    return true if(self.first_name.blank? || self.last_name.blank? || self.email.blank?)
    return false
  end

  def apply_omniauth(omniauth)
    self.email = omniauth['info']['email'] if email.blank? && !omniauth['info']['email'].blank?
    if (!omniauth['info']['first_name'].blank? && !omniauth['info']['last_name'].blank?)
      self.first_name ||= omniauth['info']['first_name']
      self.last_name ||= omniauth['info']['last_name']
    elsif (!omniauth['info']['name'].blank?)
      name_array = omniauth['info']['name'].split(' ')
      self.first_name ||= name_array.first
      self.last_name ||= name_array[1..name_array.length].join(' ')
    end
    set_photo_from_url(omniauth['info']['image'])
    self.authentications.build(provider: omniauth['provider'], uid: omniauth['uid'], token: (omniauth['credentials']['token'] rescue nil), secret: (omniauth['credentials']['secret'] rescue nil)) if !self.persisted? || !self.authentications.exists?(provider: omniauth['provider'], uid: omniauth['uid'])
  end

  private

  def set_first_admin
    self.is_admin = true if User.where(is_admin: true).count == 0
  end

  def activate
    self.has_induction = true
  end

end

app/controllers/admin/users_controller.rb
# require Sitebootstrapperv2::Engine.root.join('app', 'controllers','admin', 'users_controller')
class Admin::UsersController < Admin::AdminController

  def index
    if params[:user_id] && params[:user_id].to_i > 0
      @users = User.where(:id => params[:user_id]).paginate(:page => params[:page], :per_page => 50)
    else
      @users = User.order('first_name, last_name').paginate(:page => params[:page], :per_page => 50)
    end
  end

  def users_filter
  	if(params[:voluntary_id].present?)
  		@users = User.where('id = ? ', params[:voluntary_id]).paginate(:page => params[:page], :per_page => 50)
  	elsif (params[:email].present?)
  		@users = User.where('email = ? ', params[:email]).paginate(:page => params[:page], :per_page => 50)			
  	else
  		@users = User.order('created_at desc').paginate(:page => params[:page], :per_page => 50)	
  	end
  	respond_to do |format|
     format.html {}
     format.js { render :index }
    end
  end

  def resend_activation
    @user = User.find(params[:id])
    @user.send_confirmation_instructions
    #render :json => {:status => 1, :user_name => user.full_name}
  end

  def login_as
    new_user = User.find(params[:id])
    session["admin_user_id"] = current_user.id
    sign_in(:user, new_user)
    redirect_to root_path
  end

  def make_admin
    user = User.find(params[:id])
    user.update_attribute(:is_admin, true)
    flash[:ok] = "User #{user.email} is now admin"
    redirect_to admin_users_path
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:ok] = "User #{user.email} deleted"
    redirect_to admin_users_path
  end

  def to_csv
    users = User.order('last_name, first_name')
    csv_string = "Name, Email, Create at, Status, Last login, Role\r\n"
    users.each do |user|
      csv_string << "#{user.full_name}, #{user.email}, #{user.created_at.strftime("%Y-%m-%d %H:%M")}, #{user.status}, #{(user.last_sign_in_at ? user.last_sign_in_at.strftime("%Y-%m-%d %H:%M"):"never")}, #{(user.is_admin? ? 'Admin' :'')}\r\n"
    end
    send_data csv_string, :type => "text/csv; charset=utf-8; header=present", :filename => "user_accounts_#{Time.now.strftime("%m-%d-%Y")}.csv", :disposition => 'attachment'
  end

  def chart_data
    data = []
    days_to_show = 90
    (0..days_to_show).each do |offset|
      day = Time.now - (days_to_show-offset).days
      if(params[:type] == 'day')
        count = User.where(:created_at => day.beginning_of_day..day.end_of_day).count
      elsif(params[:type] == 'sum')
        count = User.where('created_at <= ?', day.end_of_day).count
      end
      data << [day.to_time.to_i * 1000, count]
    end

    render :json => {:type => params[:type], :data => data}
  end

  private

  def user_params

  end

end

app/views/admin/users/_users.html.haml
%br
%table.table.table-striped
  %tr
    %th Name
    %th Email
    %th Create at
    %th Send email
    %th Status
    %th Role
    %th Login as
    %th 
  - @users.each do |user|
    %tr
      %td= user.full_name
      %td= user.email
      %td= user.created_at.strftime("%Y-%m-%d %H:%M")
      %td= user.status
      %td= link_to('resend activation', resend_activation_admin_user_path(user.id), :class => 'resend_activation', :remote => true) if !user.active_for_authentication?
      %td= (user.is_admin? ? 'Admin' : link_to('make admin', make_admin_admin_user_path(user.id), data: {confirm: "Are you sure you want to make user: #{user.email} an admin?"}, method: :post))
      %td= link_to "login as", login_as_admin_user_path(user.id)
      %td= button_to "delete", admin_user_path(user.id), data: {confirm: "Are you sure you want to delete user: #{user.email}?"}, method: :delete
  = page_entries_info @events
  = will_paginate @events

app/views/admin/users/index.haml
.container.admin
  = render 'shared/navigation_admin'
  .row
    .col-lg-12
      .chart
        %h3.module_header
          Usuarios
    .col-lg-12
      .well
        .row
          = form_tag users_filter_path, method: 'get', remote: true do
            .col-lg-1
            .col-lg-1.pull-left
              %br
              %br
              Busqueda:
            .col-lg-3
              .row
                .col-lg-12.pull-left
                  .input-group.input-group-sm
                    %label Voluntario:
                    %br
                    = text_field_tag :user_name, '', class: 'form-control', placeholder: "Nombre"
                    = hidden_field_tag :voluntary_id, @voluntary_id
            .col-lg-3
              .row    
                .col-lg-12.pull-left
                  .input-group.input-group-sm
                    %label Email:
                    %br
                    = text_field_tag :email, '', class: 'form-control', placeholder: "e-mail"
            .col-md-1.pull-left 
              %br
              %button.btn.btn-succes{type: "submit", value: "Search",style:"margin-top:15px"}
                %i.glyphicon.glyphicon-search
            .col-md-3  
              = link_to 'Export to CSV', to_csv_admin_user_path(0), style: "float:right;", class: 'btn btn-default'
        .report-content
          = render 'users' 

          
- content_for :js_footer do
  :javascript
    $(function() {
      $('input.datepicker').datepicker({
        dateFormat: "yy-mm-dd",
        changeMonth: true,
        changeYear: true,
        minDate: '-12M',
        maxDate: "0"
      });         
      $('#user_name').autocomplete({
        source: "#{admin_responsable_autocomplete_path}",
        minLength: 1,
        select: function( event, ui ) {
          $(this).css("border-color","#9FF781");
          if(ui.item) {
            $("#voluntary_id").val(ui.item.id);
          } else {
            return false;
          }
        }

      }).blur(function() {
        if($(this).val() === ""){
          $(this).css("border-color","#fff");
          $("#voluntary_id").val("");
        }

      });
    });

app/views/admin/users/index.js.haml
$('.report-content').html("#{j render 'users'}");

app/views/admin/users/resend_activation.js.haml
alert('Resent activation to: #{@user.full_name}');